name: Simple Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Build Docker Image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build from devsecops-analyzer folder
        run: docker build -t devsecops-analyzer ./devsecops-analyzer
