name: DevSecOps Analyzer CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-python:
    name: Python Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8 on app/
        run: flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

  scan-gitleaks:
    name: Scan Repo with Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  build-and-scan-image:
    name: Docker Build + Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        run: docker build -t devsecops-analyzer .

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@v0.11.2
        with:
          image-ref: devsecops-analyzer
          format: table
          severity: HIGH,CRITICAL
          scan-type: image

  test-api-endpoints:
    name: Verify Container Health
    runs-on: ubuntu-latest
    needs: build-and-scan-image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Container
        run: |
          docker run -d -p 5000:5000 --name analyzer devsecops-analyzer
          sleep 10
          docker ps

      - name: Test /healthz Endpoint
        run: |
          curl -s http://localhost:5000/healthz | grep '"status": "ok"'

      - name: Test /apidocs Swagger Route
        run: |
          curl -s http://localhost:5000/apidocs | grep '<title>'
