name: Final Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: Build DevSecOps Image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image from correct folder
        run: docker build -t devsecops-analyzer ./devsecops-analyzer
