name: DevSecOps Analyzer CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    name: Build Docker Image & Run Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image from subfolder
        run: docker build -t devsecops-analyzer ./devsecops-analyzer

      - name: Run Gitleaks CLI scan
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          ./gitleaks detect --source ./devsecops-analyzer --no-banner

      - name: Install and Run Trivy CLI scan
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          ./trivy image devsecops-analyzer

      - name: Run flake8 on Flask backend
        run: |
          pip install flake8
          flake8 devsecops-analyzer/app/ --exit-zero --count --show-source --statistics
